on: [push, pull_request]

jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    services:
      sonic:
        image: valeriansaliou/sonic:v1.1.9
        ports:
          - 1491:1491
        volumes:
          - sonic.cfg:/etc/sonic.cfg
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Check PHP Version
      run: php -v
    - name: Composer install
      run: composer install
    - name: Run phpunit
      run: ./vendor/bin/phpunit
